### PR TITLE
UI z-index & failed import fix

### PR DESCRIPTION
**Pull request by DadoIrie**
the FAILED IMPORT isn't really a big deal as it doesn't break the galleries functionality ... just removing the error message with the proper declaration as how comfyui expects it

the z-index fix is needed, because the folder buttons got covered by another extension (https://github.com/11cafe/comfyui-workspace-manager)

appreciating that someone forked and expanded one my favorite comfyui extension and made those changes for myself, but thought other might appreciate those small fixes too 
feel free improving or handling those issues otherwise ... or just merge this PR ;)

### CODE REVIEW

**Comment by DadoIrie** [comment]
the query selector of the previous clear button wasn't working anymore and therefore changed it into a id query selector with the current updated comfyui frontend
also instead of the svg icon using text on the button for consistency sake with the other buttons

also placing the button at the bottom is more intrusive as the other workflow related buttons are most likely more frequently used - has tho its downsides as explained in the comments related to that

another option would be placing the gallery button before the save button 

besides the clear button query fix feel free uncommenting/changing/altering as you please the suggestions (of course I highly recommend going over those changes related to the comfy-menu button placement and clearing the code as you see fit)

**Comment by wogam** [comment]
Thanks for the changes, I will look into them. 

- I didn't change the init file (just basics) from the original which is where the error stems from lol. 
- In terms of the z-index I'll have to look into it because the other z-indexes (move overlay, etc) need to be realigned to fit that. 
- For the gallery button I used the alignment with the clear button due to conflicts with other scripts but i'll re-evaluate and keep you posted.

**Comment by DadoIrie** [comment]
the init file is good to go and that small change (using empty dictionary instead of empty list) is just to fix the failed import error during comfyui backend launch/restart - it has no impact on the overall functionality of the image gallery whatsoever, because it doesn't even import any custom nodes

regarding the gallery button I actually just wanted to fix the query selector and query the id instead in order to align with the major frontend update, but then saw also that it uses a svg icon instead of the text, which did not really fit into the menu - and than I got a bit carried away and that's way it is a bit of a mess (and currently with the PR it is as follows with some comments here and there, but shouldn't be to hard nor time-consuming understanding it - just, as mentioned, adjustments and cleanup of that part of the code is required - I just gave you another options besides the clear button approach) 
image

regarding the z-index there must be a cleaner way to increase it for the parent only and then children are on top of it without needing to increase their z-index too

**Review by wogam — APPROVED** [review]

**Comment by DadoIrie** [comment]
this should resolve it with the z-index

**Review by wogam — APPROVED** [review]

**Comment by tbcarver** [comment]
@wogam Hello, can you please merge these changes into main?  This also has a fix for the issue I reported https://github.com/wogam/image-gallery-comfyui/issues/8

Thanks!

**Review by wogam — CHANGES_REQUESTED** [review]
Can you please refactor the code so that the original button in the new menu is visible. The old menu is set to be depreciated.

**Comment by wogam** [comment]
> @wogam Hello, can you please merge these changes into main? This also has a fix for the issue I reported #8
> 
> Thanks!

I've merged the PR

**Comment by DadoIrie** [comment]
> Can you please refactor the code so that the original button in the new menu is visible. The old menu is set to be depreciated.

more clarification please, because I have no troubles and do see the gallery button even after right now fetching the latest commits from comfyui ... besides that it is tested only on the updated front-end - if launching with or without `--front-end-version Comfy-Org/ComfyUI_frontend@latest` argument doesn't really matter since comfyui by default uses that front-end now - with that argument comfyui is launched with the latest release of that front-end ... meaning that the deprecation is not relevant here since it is targeting that updated front-end (and I'm not planning to backport it either - just a side note)

unless you mean something else

**Comment by tbcarver** [comment]
@dadoirie  I think @wogam is referring to the new beta menu option that removes the side bar and added a top bar.  That needs to be turned on in the settings of ComfyUI after updating.

**Comment by tbcarver** [comment]
> @wogam

It would be best to open an issue for new UI getting a open gallery button.  I can help as well.

**Pull request closed without merging**
